# Generated by Django 4.0.1 on 2022-02-08 14:05

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import django_extensions.db.fields
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Context',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.CharField(max_length=512, primary_key=True, serialize=False, verbose_name='Identifier (Context)')),
                ('type', models.CharField(max_length=30)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=512, populate_from='id')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JSONResource',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50)),
                ('data', models.JSONField(blank=True)),
            ],
            options={
                'ordering': ['-modified'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Indexables',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource_id', models.UUIDField()),
                ('type', models.CharField(max_length=64)),
                ('subtype', models.CharField(max_length=256)),
                ('group_id', models.CharField(blank=True, max_length=512, null=True, verbose_name='Identifier for grouping indexables, e.g. by vocab identifier')),
                ('content_id', models.CharField(blank=True, max_length=512, null=True, verbose_name='Identifier (URL/URI/URN) for the content, if it has one')),
                ('indexable', models.TextField()),
                ('indexable_date_range_start', models.DateTimeField(blank=True, null=True)),
                ('indexable_date_range_end', models.DateTimeField(blank=True, null=True)),
                ('indexable_int', models.IntegerField(blank=True, null=True)),
                ('indexable_json', models.JSONField(blank=True, null=True)),
                ('indexable_float', models.FloatField(blank=True, null=True)),
                ('original_content', models.TextField()),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('language_iso639_2', models.CharField(blank=True, max_length=3, null=True)),
                ('language_iso639_1', models.CharField(blank=True, max_length=2, null=True)),
                ('language_display', models.CharField(blank=True, max_length=64, null=True)),
                ('language_pg', models.CharField(blank=True, max_length=64, null=True)),
                ('selector', models.JSONField(blank=True, null=True)),
                ('resource_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.AddIndex(
            model_name='indexables',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='search_serv_search__d642e8_gin'),
        ),
        migrations.AddIndex(
            model_name='indexables',
            index=models.Index(fields=['content_id'], name='search_serv_content_83f514_idx'),
        ),
        migrations.AddIndex(
            model_name='indexables',
            index=models.Index(fields=['resource_id'], name='search_serv_resourc_794531_idx'),
        ),
        migrations.AddIndex(
            model_name='indexables',
            index=models.Index(fields=['language_iso639_2', 'language_iso639_1', 'language_display'], name='search_serv_languag_985c2a_idx'),
        ),
        migrations.AddIndex(
            model_name='indexables',
            index=models.Index(fields=['type'], name='search_serv_type_abf02f_idx'),
        ),
        migrations.AddIndex(
            model_name='indexables',
            index=models.Index(fields=['subtype'], name='search_serv_subtype_3ca12d_idx'),
        ),
        migrations.AddIndex(
            model_name='indexables',
            index=models.Index(fields=['group_id'], name='search_serv_group_i_e97823_idx'),
        ),
        migrations.AddIndex(
            model_name='indexables',
            index=models.Index(fields=['type', 'subtype'], name='search_serv_type_4d1b70_idx'),
        ),
        migrations.AddIndex(
            model_name='indexables',
            index=models.Index(fields=['type', 'subtype', 'group_id'], name='search_serv_type_628ea6_idx'),
        ),
        migrations.AddIndex(
            model_name='indexables',
            index=models.Index(django.db.models.functions.text.Upper('type'), name='uppercase_type'),
        ),
        migrations.AddIndex(
            model_name='indexables',
            index=models.Index(django.db.models.functions.text.Upper('subtype'), name='uppercase_subtype'),
        ),
        migrations.AddIndex(
            model_name='indexables',
            index=models.Index(django.db.models.functions.text.Upper('type'), django.db.models.functions.text.Upper('subtype'), name='uppercase_type_subtype'),
        ),
        migrations.AddIndex(
            model_name='indexables',
            index=django.contrib.postgres.indexes.HashIndex(fields=['indexable'], name='search_serv_indexab_d3e10c_hash'),
        ),
    ]
