# Generated by Django 4.0.1 on 2022-01-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexables',
            name='group_id',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Identifier for grouping indexables, e.g. by vocab identifier'),
        ),
    ]
