# Generated by Django 4.0.1 on 2022-01-31 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_service', '0002_indexables_group_id'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='indexables',
            name='uppercase_indexables',
        ),
        migrations.AddIndex(
            model_name='indexables',
            index=models.Index(fields=['group_id'], name='search_serv_group_i_e97823_idx'),
        ),
        migrations.AddIndex(
            model_name='indexables',
            index=models.Index(fields=['type', 'subtype', 'group_id'], name='search_serv_type_628ea6_idx'),
        ),
    ]
