# Generated by Django 4.1.4 on 2023-01-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_service', '0002_context_indexable_contexts_jsonresource_contexts'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsonresource',
            name='type',
            field=models.CharField(default='', max_length=64),
        ),
    ]
